### ISSUE TITLE
例假互动的reivew

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#10]
背景：https://github.com/sibbay-ai/public/issues/139#issuecomment-369120598
目的：例假互动review
@fushang318 size:0.3 deadline:2018-03-01

**Comment by bqx619** [comment]
@bqx619

**Comment by fazhen** [comment]
1.建议根据年龄甄选尚未初潮女性和已绝经女性

是否已经月经来潮？（限定年龄12-15）
是
否
是否已经绝经？（45-55）
是
否
如果是尚未来潮女婴或已经绝经妇女，不必进一步追问

2.输入有时间限制？打开后，长时间不予输入数据，会自动默认已经输入完成。

3.问询不规范，可参考：
“上次月经来潮是哪一天？”
“月经持续时间为多久？”
“月经周期是否规律？”
“经期血量如何”
“经期有无下列症状？”
“经期饮食情况如何？”

4.能否提供问询脚本及参考资料？现有问询及答案不规范，建议修改


5.为何选择经期前7天、经期中（3-7天）、经期后7天？有何特殊考量？你的记录周期是在17-21天，正常女性月经周期一般是28±7天，你的记录时间是否过于频繁；


6.经期前7天、经期中（3-7天）、经期后7天的问询脚本能否提供？
7.有研究发现月经周期不规律的发生率约10.6%，对于这一部分女性，你如何进行监测？ @fushang318

**Comment by fazhen** [comment]
李飞，我无法@吴善超，是不是权限的原因？麻烦帮我调整一下 @fushang318

**Comment by bqx619** [comment]
- 关于 **[1.]** 已经添加至 https://github.com/sibbay-ai/cooperation-issues/issues/277 作为完善
- 关于 **[2.]** 我正在尝试重现问题, 稍后在 issues 中补充
- 关于 **[3.][4.][5.][6.]** 一期开发是实现已有的问询脚本, 脚本内容在 https://github.com/sibbay-ai/cooperation-issues/issues/243 这个 issues 之中, 您可参阅, 如果相关问询有问题, issues 中可以@我做修改即可
- 关于 **[7.]** 目前在现有 m-lang 之下的开发, 我的思考是做一个前置问询, 放在第一次的互动之中, 如果确定月经不规律, 那么可以要求用户给一个大概的模糊期, 然后取消经期前7天的问询, 在模糊期之内每日问询确定例假时间, 当然这只是一个初步想法, 需要讨论实现
