### ISSUE TITLE
小白功能介绍视频修改

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#116]
主要工作：录制新的视频、提供修改意见、修改视频脚本

**Comment by fazhen** [comment]
申请开发 deadline：2018-07-15 size：0.3 @fushang318

**Comment by fazhen** [comment]
详见：
https://shimo.im/docs/2uRxzf8fPDQCkc1v
https://shimo.im/docs/f36745119a394935 @fushang318

**Comment by fazhen** [comment]
变更 deadline：2018-08-15 @fushang318 合并时间晚于截止日期

**Comment by fushang318** [comment]
变更 deadline：2018-08-15
