### ISSUE TITLE
“血压，您真的会测量吗？”文章撰写及推送

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#119]
主要工作：“血压，您真的会测量吗？”文章撰写及推送

**Comment by fazhen** [comment]
申请开发 deadline：2018-08-15 size：0.5 @fushang318

**Comment by fazhen** [comment]
详情见：
https://mp.weixin.qq.com/s/hfnbPfCggF6qkDDtJPo9kg
@fushang318

**Comment by fushang318** [comment]
1
