### ISSUE TITLE
“血压，您真的会测量吗？|仪器选择”文章撰写

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#125]
主要工作：“血压，您真的会测量吗？|仪器选择”文章撰写、编辑及推送

**Comment by fazhen** [comment]
申请开发 deadline：2018-08-15 size：0.5 @fushang318

**Comment by fazhen** [comment]
文章已经推送，详情见：https://mp.weixin.qq.com/s/bypzM-PnxnPuk1_QttT2SA
@fushang318

**Comment by fushang318** [comment]
@fazhen  reopen 干嘛？
