### ISSUE TITLE
新症状添加及审核操作流程

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#13]
背景：https://github.com/sibbay-ai/medical/issues/9
目的：规范症状添加及审核操作流程
@alisahuxu size:0.5 deadlinee:2018-03-03

**Comment by fazhen** [comment]
详见https://shimo.im/folder/p6UjvF2IR9YRyGyS
@alisahuxu @shero3

**Comment by shero3** [comment]
OK，请发PR以便之后统计工作量
