### ISSUE TITLE
医学组PR介绍

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#142]
主要工作：再次向医学组同事介绍PR相关内容，反复演示pr建立过程并解答相关疑问

**Comment by fazhen** [comment]
申请开发 deadline：2018-08-15 size：0.2 @fushang318

**Comment by fazhen** [comment]
主要成果：
三位计划引进的同事中
金老师已基本掌握icp流程，计划明天正式引入icp系统；
另外两位同学，暂时表示理解，尚需进一步操作观察。
详见：https://shimo.im/docs/cJ6HYpEuTtgkVOrk/ 《pr讲解》，可复制链接后用石墨文档 App 打开
@fushang318

**Comment by fushang318** [comment]
把 金老师 github 账号给我，我需要修改 ICP 系统的 白名单
