### ISSUE TITLE
医学问询互动脚本中的 bmesh 值使用要注意

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/medical#144]
来自：https://github.com/sibbay-ai/qa-defects/issues/222

原来给 头痛  写的医学问询互动（excel 表格那个）

其中伴随症状  发热用了  snomed-sctid-386661006  , 这个 bmesh ，但是系统中的 症状库并没有这个 bmesh 
这会导致用户的日记中出现 none （没有）这个错误的数据
![image](https://user-images.githubusercontent.com/326242/43748582-def44950-9a22-11e8-889c-fe8b5fb67d7c.png)

我翻阅了一下 以前写的 10个 医学问询互动，其中应该大量的用到了系统里没有的 bmesh
一旦用户录入了这些信息都会导致这个问题

**所以以后再写医学问询互动时使用的 bmesh 一定要保证系统库中有** 

@fazhen 请知晓

**Comment by fazhen** [comment]
好的，我已知晓 @fushang318
