### ISSUE TITLE
小白记录样例

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#145]
主要内容：自从小白健康记录上线以来，记录者数量陆续增加，记录内容及方式以自发为主，记录的主动性及系统性有待增强，亟待推出正确记录方式的参考样例，让记录者更为具体而清晰地理解并见证客观、及时、准确的记录，不仅可以为自己保留一份完整的健康记录档案，更重要的是会获得“意外惊喜”（一份优质的记录，可以第一时间获得精准建议、调整生活方式、接受医院诊疗，获取更多的健康成就）。制作小白记录样本，还可以为后期推广助力，吸引更多记录者加入并增加记录者粘性。@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-08-15 size：0.5 @fazhen

**Comment by kimgrace6** [comment]
相关工作成果详见：https://shimo.im/docs/a6e542c13b9042d9/ 点击链接查看「记录样例」，或复制链接用石墨文档 App 打开@fazhen

**Comment by fazhen** [comment]
李飞，已打标签，请修改 @fushang318

**Comment by fazhen** [comment]
金老师，我已经合并，请关闭该issue @kimgrace6
