### ISSUE TITLE
健康记录专家备案信息

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#146]
主要工作：培训一名新的健康记录专家，经测试后进入健康记录专家群  @fushang318

**Comment by fazhen** [comment]
新增专家备案信息：https://shimo.im/sheet/i2zqWCen3yoEe4oE/RIDOC
请统计2018年8月3号凌晨至2018年8月10号凌晨，健康记录专家留言情况
@fushang318

**Comment by fushang318** [comment]
已经增加了
