### ISSUE TITLE
审核“周明星评选规则调整20180810”

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#154]
主要内容：针对@fazhen的”周明星评选规则调整20180810“提出补充建议，引入权重法到周明星评选工作中，提高科学性、严谨性，确保公正、公平。https://github.com/sibbay-ai/medical/issues/153@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-08-15 size：0.1 @fazhen

**Comment by kimgrace6** [comment]
工作成果详见：https://shimo.im/docs/FJVPgENZE5sqDqMC/ 《周明星评选规则调整20180810》，可复制链接后用石墨文档 App 打开

**Comment by fazhen** [comment]
金老师，这个issue 要有pr @kimgrace6

**Comment by fazhen** [comment]
李飞，已打标签，请修改 @fushang318

**Comment by fazhen** [comment]
金老师，这个我已经合并，次issue你可以关闭了
