### ISSUE TITLE
制订小白健康记录专家公约

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#158]
主要内容:随着小白健康记录专家留言量的增加，与小白建康价值观及设立初衷存在冲突的回复留言及周明星评选违规现象相继出现，为确保小白的可持续发展，增进小白健康记录专家对小白的深刻理解、更好地完成健康记录回复工作，特此制订“小白健康记录专家公约”，明确责任、权利及义务，使得现有及日后加入的健康记录专家在遵守“小白健康记录专家公约”的前提下开展工作，以便更好地为记录者服务。@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline:2018-08-31 size:1@fazhen

**Comment by kimgrace6** [comment]
相关工作成果详见：https://shimo.im/docs/4510e89d47d44f4b/ 点击链接查看「小白记录专家公约」，或复制链接用石墨文档 App 打开@fazhen

**Comment by fazhen** [comment]
已经在小白站会群内进行意见征集 @kimgrace6

**Comment by fazhen** [comment]
记录专家公约已经制作完成，经过组内两轮审核及站会群组内征询意见，现已成定稿，请人事存档：
https://shimo.im/docs/4510e89d47d44f4b/
@shero3

**Comment by fazhen** [comment]
已经完成审核，请 @fushang318 修改标签

**Comment by fushang318** [comment]
@fazhen 好了

**Comment by fazhen** [comment]
金老师，该issue可以关闭了 @kimgrace6

**Comment by fushang318** [comment]
update
