### ISSUE TITLE
例假互动脚本review

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#17]
上次例假互动MRI审核后发现部分问询不合理https://github.com/sibbay-ai/medical/issues/10
从医学角度对脚本进行了修改，希望对此份互动有所帮助 
@fushang318 size：0.4 deadline:2018-03-14

**Comment by fazhen** [comment]
小白:您好，在小白对您的例假进行管理前，需要问您几个小问题？
【初次登录，进行资料录入】
等在500毫秒
甄选问询：
是否已经月经来潮？（年龄在12-15的女性，问询该问题）
是（继续问询）
否（停止问询）
是否已经绝经？（年龄在45-55的女性，问询该问题）
是（继续问询）
否（停止问询）
A：现在是否处于经期中？
A-1：是 A-2：否
AB:本次月经持续多久了?
【选择A-1】
<输入天数>
XX天
AC：上次月经来潮是在几号？
【选择A-2】
Wheel输入日期：15号 （默认）
B:月经持续时间一般是几天？
<输入天数>
XX天
C：月经期血量如何？
C-1：月经量很多 C-2：月经量偏多
C-3：月经量正常 C-4：月经量偏少
C-5：月经量很少
D:月经前后或月经期精神状态如何？
<多选>
D-1：疲乏困倦 D-2：烦躁易怒 D-3：精神紧张 
D-4：心情忧郁 D-5：失眠  D-5：都没有
E.月经前后或月经期有无如下躯体症状？
E-1：头晕
E-2：头痛
E-3：乳房胀痛
E-4：手、足、眼睑水肿
E-5：腹胀
E-6：恶性、呕吐
E-7：腰骶部疼痛
E-8：腹泻
E-9：便秘
E-10：尿频
E-11：都没有
F月经前后或月经期有无如下表现？
F-1：出汗
F-2：眩晕
F-3：心悸
F-4：都没有
G月经前后或月经期食欲如何？
G-1：食欲增加
G-2：厌食
G-3：饮食如常
H.月经前后或月经期皮肤情况
H-1：油性皮肤
H-2：痤疮
H-3：皮疹
H-4：头皮多油
H-5：头皮干燥
H-6：无明显变化

I：您希望小白在以下哪些方面对您进行管理呢？
I-1:只记录经期数据
I-2:现在备孕中 =>调用备孕管理bunch
I-3:怀孕中 =>调用孕期管理bunch
小白已经记录，会对经期管理提醒
例假管理bunch2
小白:您好，欢迎回来，小白想再问您两个问题？
【久不登录，重新回来】
等在500毫秒
A：上次月经来潮是几号？
【定位最新经期时间】
Wheel输入日期：15号 （默认）
B:上次月经持续几天？
<输入天数>
XX天
根据登录时间判断，距离例假开始还有7天
{对话形式}
小白：还有一周就要到月经期喽，要提前做准备啦
客户：恩恩，是的呢，还好小白你提醒我了
小白：不客气呢，这几天不要吃冰的东西哦，以免出现痛经哦
客户：小白你好细心哦，么么哒
C:还有一周就要到月经期喽，还记得要做什么准备吗?
C-1:要做什么准备?我都忘记了！
C-2：哈哈，还好小白提醒我了，谢谢小白了!
CA:这几天不要吃冰的东西哦，以免经期出现痛经
【选择C-1】
小白你好细心哦，么么哒
CB:虽然您都了解了，但这几天还是不要吃冷食，以免痛经哦
【选择C-2】
小白你好细心哦，么么哒
根据登录时间判断，距离月经来潮还有6天
{对话形式}
小白：今天离月经来潮又近了一点，还有6天哦
客户：恩恩，现在已经注意啦，没有吃冷的东西
小白：好棒哦，不过还要注意作息规律，不要熬夜哦
客户：好的，都听小白的，亲亲
D:还有6天就要月经来潮了，您还记得今天需要注意什么吗？
D-1：不吃冷食 D-2：作息规律，不要熬夜
DA:主人好棒，都记住了
【选择D-1】
DB:好棒噢，一定要作息规律，才有精神呦
【选择D-2】
根据登录时间判断，距离月经来潮还有5天
{对话形式}
小白：没有熬夜吧？
客户：没有的，都按时休息了
小白：棒棒哒，最近也不要太劳累了，要注意休息！
客户：知道了，会尽量休息，减少劳动量的。
E：您没有熬夜吧？
E-1：当然没有，都按时休息了 E-2：这两天精神不济，没休息好
EA:棒棒哒，最近也不要太劳累了，要注意休息！
【选择E-1】
EB：临近月经来潮，一定要保持足够的休息时间啊
【选择E-2】
根据登录时间判断，距离月经来潮还有4天
{对话形式}
小白：昨天休息的怎么样？
客户：很好啊，都没怎劳累，很轻松的
小白：好赞，还有4天月经来潮，今天开始不要喝浓茶或咖啡喽
客户：不喝咖啡好困的
小白：咖啡或者茶对于现在您来说，刺激性太大了，要注意
客户：好吧，听小白的
F：昨天休息的怎么样？
F-1：听你的，开始早睡早起了
F-2：还好，不累，很轻松
FA：好赞，还有4天月经来潮，今天有没有喝浓茶或咖啡噢？
【选择F-1，F-2】
FA-1：没有 FA-2：有
FAA：好棒，继续保持哦，不要喝刺激性强的东西
【选择FA-1】
FAB:咖啡或者茶对于现在您来说，刺激性太大了，要注意了
【选择FA-2】
根据登录时间判断，距离月经来潮还有3天
{对话形式}
小白：这几天没有喝咖啡提神吧？
客户：这几天暂时戒掉啦
小白：这就对了，最近要保持心情愉快，情绪不能太激动
客户：恩恩，会按你说的办的
G：今天有没有喝咖啡提神啊？
G-1：有 G-2：没有
GA：短时间内还是不要喝了，对现在这个时期来说，刺激性太强了
【选择G-1】
GB：这就对了，最近还要保持心情愉快，情绪不能太激动
【选择G-2】
根据登录时间判断，距离月经来潮还有2天
{对话形式}
小白：最近心情怎么样啊？
客户：还挺好的，还有什么要注意的吗？
小白：要用热水泡泡脚，有助于血液循环的
客户：恩恩，晚上睡前会泡脚的，嘻嘻
H：最近心情怎么样啊？
H-1：很好啊 H-2：一般 H-3：不好
HA：心情愉快就好，没事勤用热水泡泡脚，有助血液循环
【选择H-1】
HB：最近这短时间要调整好心态，保持心情愉快哦
【选择H-2，H-3】
根据登录时间判断，距离月经来潮还有1天
{对话形式}
小白：马上就到月经期啦，千万要记得带卫生棉哦
客户：早就准备好了，这个不会忘记的，嘻嘻
小白：哈哈，比心，前几天的注意事项也要记好哦
客户：了解的，比心
I：马上就到月经期啦，有没有带卫生棉哦
I-1：肯定带了 I-2：还好小白提醒，不然都忘了
IA：哈哈，比心，前几天的注意事项也要记好哦
【选择I-1】
IB：记得就好，前几天的注意事项也要记好哦，比心
【选择I-2】
根据登录时间判断，月经第一天
{对话形式}
小白：现在已经处在月经期啦，不要吃冷的食物，要多喝热水哦
客户：谢谢小白提醒呢！亲亲
小白：今天有没有出现痛经的症状呢？
客户：症状轻很多啊，小白你之前的提醒，很有效哦
小白：哈哈，再准备个暖手宝捂住肚子，会缓解更多的
A：现在已经处在月经期啦，今天有没有出现痛经的症状呢？
A-1：没有 A-2：疼痛减轻了 A-3：还是很痛
AB：不错，棒棒哒
【选择A-1】
AC：再准备个暖手宝捂住肚子，会缓解更多的
【选择A-2】
AD：那一定不要吃冷的食物，多喝热水，准备暖手宝捂住肚子
【选择A-3】
根据登录时间判断，例假第二天
{对话形式}
小白：今天怎么样，有没有出现腰酸背痛等症状？
客户：恩恩，对啊，我还用手捶捶腰背进行缓解呢?
小白：快不要这么做了，这样会让酸痛更严重的
客户：阿，怎么还会更严重啊？
小白：这样会使得盆腔充血，月经延长，酸痛更严重
B：今天怎么样，有没有出现腰酸背痛等症状？
B-1：有 B-2：没有
BA：千万不要用手捶腰背，否则会使得盆腔充血，月经期延长，酸痛更严重
【选择B-1】
BB：身体棒棒的
【选择B-2】
根据登录时间判断，例假第三天
{对话形式}
小白：腰背酸痛缓解一些了吗？
客户：今天缓解一点，没那么严重了
小白：这是正常的，像腰酸，嗜睡，面部浮肿等
小白：这些都不需要特意治疗的
客户：恩恩，知道了，小白
C：腰背酸痛缓解一些了吗？
C-1：缓解好多 C-2：没有缓解
CA：像腰酸，嗜睡，面部浮肿等，一般经来自消，不需特殊治疗。
【选择C-1】
CB：像腰酸等，不需要特意治疗，经期结束就会恢复
【选择C-2】
根据登录时间判断，月经期第四天
{对话形式}
小白：经期基本上过半了，还要继续注意保暖呢
客户：恩恩，一直都在用热水烫脚呢
小白：还要尽量少坐在阴凉及空调的风口处
客户：哦哦，这个还真没注意，谢谢小白了
D：经期基本上过半了，您有没有继续注意保暖呢？
D-1：有的，一直在用热水烫脚 D-2：没有
DA：不只这些，还要尽量少坐在阴凉及空调的风口处
【选择D-1】
DB：要继续注意保暖啊，以免痛经哦
【选择D-2】
根据登陆时间进行对比，处在月经期第五天
{对话形式}
小白：本月的经期快结束喽，如果有需要拔牙之类的需求可以开始预约了
客户：来例假还和拔牙有关吗？
小白：当然啦，经期的时候血小板数目会减少。
小白：如果在这个时候拔牙，可能会引发感染和大出血的哦，很严重的
客户：哇，还好小白你提醒我，么么哒
E：经期快结束了，主人接下来有没有要拔牙的打算啊？
E-1：有 E-2：没有
EA：经期拔牙可能会引发感染和大出血，您可以经期结束后预约
【选择E-1】
EB：恩恩，如果以后有拔牙需求，一定要避开月经期哦
【选择E-2】
根据登陆时间进行对比，处在经期第六天
{对话形式}
小白：今天月经期结束了吗，快要可以出去玩喽
客户：经期终于结束了，可以出去浪了，哈哈
小白：但是要注意哦，经期结束前三天不可以去游泳哦
客户：不出去游泳，我要去吃美食补充营养，哈哈
F：今天月经期结束了吗，准备好去哪玩了吗
F-1：经期终于结束了，可以出去浪了
F-2：不出去玩，在家补元气
FA：但是要注意哦，经期结束前三天不可以去游泳哦
【选择F-1】
FB：恩恩，可以多吃点鱼汤补补身体
【选择F-2】
经期管理bunch3经期结束建议
根据登录时间对比，月经期结束第一天
A：经期结束了，到补身体的最好时间了
A-1：已经开始喝红枣糖水了
A-2：现在在吃一些瘦肉，猪肝，鱼虾，肉蛋......
AB：对对，这样很补气血的
【选择A-1】
AC：这几样对补充蛋白质和铁元素来说特别有效哦
【选择A-2】
根据登录时间对比，经期结束第二天
B：今天有没有吃瘦肉，鱼虾等补充蛋白质啊？
B-1：有 B-2：没有
BA：小白推荐一个疗效更快的食补方法：黄芪鲫鱼汤，专门补气血
【选择B-1，B-2】
根据登录时间对比，经期结束第三天
C：今天有没有运动啊？
C-1：有 C-2：没有
CA：现在体的新陈代谢速度加快，运动很容易瘦哦
【选择C-1，C-2】
根据登录时间对比，经期结束第四天
D：今天减肥，体重有没有降？
D-1：有 D-2：没有
DA：虽然美丽很重要，但还是要注意健康啊
【选择D-1】
DB：就行保持，慢慢就会瘦下来的
【选择D-2】
根据登录时间对比，经期结束第五天
E：经期结束五天了，有没有去游泳呢？
E-1：有 E-2：没有
EA：棒棒哒，游泳可以锻炼身体的
【选择E-1】
EB：现在已经没什么问题了，不会感染的，放心游泳吧
【现在E-2】
根据登录时间对比，例假结束第六天
F：月经期后一周是养生和瘦身的黄金时间，有付出行动吗？
F-1：有 F-2：没有
FA：怎么样，每天锻炼是不是觉得自己又瘦又美了
【选择F-1】
FB：要付出行动啊，这周可以会有很大的成果的呦
【选择F-2】
根据登录时间对比，经期结束第七天
G：现在经期结束一周了，今天有没有吃油炸食品呢？
G-1：有 G-2：没有
GA：现在虽然可以吃油炸的食品，但是不要贪多哦
【选择G-1】
GB：其实，现在可以吃一些了，只要适量就不用担心的
【选择G-2】

**Comment by fazhen** [comment]
[例假互动脚本修改.docx](https://github.com/sibbay-ai/medical/files/1810777/default.docx)
上述文件还有修改痕迹，请以WPS打开查看 @fushang318 @bqx619

**Comment by bqx619** [comment]
@fazhen 收到

**Comment by fazhen** [comment]
这个size是不是应该有你来打？ @bqx619

**Comment by fushang318** [comment]
@fazhen 这个同理，也没有标准的做法，需要制定一个标准PR流程
