### ISSUE TITLE
“随行记录随心相伴”活动素材征集

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/medical#173]
主要内容：希望以小白健康T恤为媒介，增加小白健康贡献者和相关人员互动和凝聚力，借力推广，吸引更多人参与或关注小白健康。
参加人员：获得小白健康T恤的贡献者、健康记录专家及其他相关人员
呈现：用软文形式在微信公众号展示
参加方式：
1．“晒图+文字”的形式，上传到贡献者微信群或其它方式递交；
2．参加者需提供身穿小白健康T恤的照片，不拘形式，以阳光健康形象展示；欢迎大家有灿烂的笑容，考虑每个参与者的不同情况，接受 如用卡通形象做“面具”或其它形式的照片；
3． 对小白健康说一句你最想说的话，体现“随行记录，随心相伴”主题，不拘形式。
4. 如不上传照片的同学，也欢迎提供一句对小白祝福语。
素材征集截止时间：2018年8月20日
@fazhen

**Comment by aixinhuang** [comment]
相关工作成果详见： https://shimo.im/docs/RKziqXBQAdkeyZXt/ 点击链接查看「“随行记录，随心相伴”」，或复制链接用石墨文档 App 打开@fazhen

**Comment by fazhen** [comment]
已审核，请 @fushang318 修改标签

**Comment by fushang318** [comment]
变更 deadline：2018-09-02  时间格式没有写对

**Comment by aixinhuang** [comment]
收到。谢谢！ @fushang318

**Comment by aixinhuang** [comment]
变更 deadline：2018-09-06 @fushang318

**Comment by fushang318** [comment]
变更 deadline: 2018-09-06 @fushang318
