### ISSUE TITLE
用户奖励模型医学组内部讨论

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#177]
主要工作内容：

1.从医学角度审核合理性；
2.在现有奖励模型的基础上如何开展医学相关工作；

会议地址：https://zoom.us/j/9552592803
会议时间：2018-08-18，21:00

@kimgrace6 @aixinhuang

**Comment by fazhen** [comment]
上述相关疑问，已经解决，详见：
https://github.com/sibbay-ai/medical/issues/188#issuecomment-415950204

申请变更deadline，并合并 @fushang318

**Comment by fushang318** [comment]
变更 deadline：2018-08-31
