### ISSUE TITLE
中医“便秘”

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#19]
中医文章撰写新形式尝试。
@alisahuxu size:0.2 deadline:2018-03-31

**Comment by fazhen** [comment]
中医“便秘”文章撰写完成，但是由于兼职制作网站的原因，下载后有水印，请安排小荣后期处理及美化。
[老年性便秘.pdf](https://github.com/sibbay-ai/medical/files/1845268/default.pdf)
@alisahuxu

**Comment by alisahuxu** [comment]
@贾老师，这些文章的issue下次可以发在运营的目录下面吗？如果可以，方便我统计。




| |
alisa
邮箱：alisa_huxu@126.com
|

签名由 网易邮箱大师 定制

在2018年03月25日 20:30，fazhen 写道：

中医“便秘”文章撰写完成，但是由于兼职制作网站的原因，下载后有水印，请安排小荣后期处理及美化。
老年性便秘.pdf
@alisahuxu

**Comment by fazhen** [comment]
可以，下次，我放在那里 @alisahuxu

**Comment by alisahuxu** [comment]
好的




| |
alisa
邮箱：alisa_huxu@126.com
|

签名由 网易邮箱大师 定制

在2018年03月26日 10:41，fazhen 写道：

可以，下次，我放在那里 @alisahuxu

**Comment by fazhen** [comment]
deadline：2018-04-15

**Comment by fazhen** [comment]
统计需要，变更时间，请帮我打上size标签 @alisahuxu

**Comment by fushang318** [comment]
deadline: 2018-04-15
