### ISSUE TITLE
记录点整理及权重排序

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#201]
主要工作：根据记录点相关问题沟通结果，进行记录点整理及排序。
https://github.com/sibbay-ai/medical/issues/188

**Comment by fazhen** [comment]
申请开发 deadline：2019-09-01 size：0.2 @fushang318

**Comment by fazhen** [comment]
记录点初步分类详见：https://www.processon.com/view/link/5b86bf5ce4b075b9fe2e1c28

建议独立会议沟通 @jinniudashu @akakenle

**Comment by fazhen** [comment]
之前记录点链接有误，已重新上传 @akakenle @georgeliuyu

**Comment by jinniudashu** [comment]
@fazhen @akakenle 后续工作两位商定即可

**Comment by fazhen** [comment]
变更 deadline：2018-09-10 @fushang318
