### ISSUE TITLE
审核“小白记录专家公约”

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#202]
主要工作内容：汇同小白健康医学组成员共同审核“小白记录专家公约”，针对组内成员提出的意见和建议重新审核并修改“小白记录专家公约”@fazhen

**Comment by fazhen** [comment]
审核完成，请 @fushang318 修改标签

**Comment by fazhen** [comment]
请修改标签 @fushang318

**Comment by fushang318** [comment]
@fazhen haole

**Comment by fushang318** [comment]
变更 deadline: 2018-09-15
