### ISSUE TITLE
小白贡献者上海线下见面会

### ISSUE THREAD

**Issue by aixinhuang** [sibbay-ai/medical#205]
主要内容：
小白贡献者都在线上共事，安排一次线下小聚，好让大家面对面认识一下，喝茶聊天，畅谈交流。
参与者：在上海的贡献者
 （其它城市的贡献者，如正好在上海的也欢迎报名参加）
时间：于9月的周末某一天下午13:30-16:30
 （具体聚会日期征询后再定）

> 确定时间：9月22日（周六），下午13:30-16:30
> 聚会地点：上海市陕西南路55号（ Paras Coffee）

@fazhen

**Comment by aixinhuang** [comment]
申请开发 deadline：2018-09-02 size：0.3@fazhen

**Comment by aixinhuang** [comment]
上海小白贡献者线下小聚
确定时间：9月22日（周六），下午13:30-16:30
聚会地点：上海市陕西南路55号（ Paras Coffee）
9月22日前，可以在这里或贡献者群里继续报名
![paras coffee](https://user-images.githubusercontent.com/36331620/45587384-5a0de500-b937-11e8-9747-d902dc6fb492.jpg)

**Comment by aixinhuang** [comment]
“上海小白贡献者线下小聚活动”，申请变更 size：0.5
变更原因：评估超出预期
@fazhen

**Comment by fazhen** [comment]
请修改标签 @fushang318

**Comment by fazhen** [comment]
申请变更deadline：2018-10-15，变更原因：未能及时合并 @fushang318

**Comment by fushang318** [comment]
变更 deadline：2018-10-15
