### ISSUE TITLE
“血压升高”用户流程图

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#21]
血压升高的用户，在使用小白健康的流程图
https://www.processon.com/view/link/5ab6fea0e4b0d165d5b43e48
@alisahuxu size 0.8 deadline 2018-04-01

**Comment by fazhen** [comment]
这是我整理的高血压流程图，可能有部分患者像并未覆盖，请各位审核，如有修改意见，请在这里补充，我将及时修改。非常感谢！ @sibbay-ai/all

**Comment by fushang318** [comment]
@fazhen 
医学专业内容虽然我看不懂，但是我觉得这个流程图的思路很严谨，更像是一个医生问诊的流程
我在想这种医学问诊是否很常见，是否适合做成互动内容
以前刘总提到过，小白不做诊断

@georgeliuyu 能否详细的说明一下不做诊断的初衷吧，非常抱歉，我以前应该领会您的核心思想__

**Comment by georgeliuyu** [comment]
@fushang318 我们不做诊断的原因是不做没有依据判断。

**Comment by georgeliuyu** [comment]
@fushang318 你看看下一步如何推进？

**Comment by fushang318** [comment]
@georgeliuyu 如果您感觉这种有依据的问诊诊断可以做，那么这个流程图下一步可以去做 botmock

**Comment by fazhen** [comment]
这个流程图涉及的是用户可以直接回答的问题，在每一支线的最后给出的都是建议，未做医学诊断。现有流程图略显粗糙，可以根据结合实际制作情况做调整，问询方式也可以再人性化一些。有需要我协助的，可以随时联系我。 @fushang318

**Comment by fushang318** [comment]
@fazhen 额，略显粗糙是什么意思，你可以继续细化吗？

**Comment by fazhen** [comment]
我可以根据设计场景再做细化，我看一下这个例子后，再给你回复 @fushang318

**Comment by fazhen** [comment]
我看了一下这个例子，和我的流程图差不多，我可以来做这部分工作；后期再由文案人员对情感性文字进行润色吧。 @fushang318

**Comment by fushang318** [comment]
@fazhen 嗯，可以尝试一下，你先自己注册一个账号，试试吧

**Comment by fazhen** [comment]
deadline:2018-04-15  统计需要，申请变更时间 @fushang318

**Comment by fazhen** [comment]
deadline:2018-04-15

**Comment by fazhen** [comment]
统计需要，申请变更时间 @fushang318

**Comment by fushang318** [comment]
deadline:2018-04-15
