### ISSUE TITLE
ICP认证培训

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#215]
主要工作：培训非开发人员ICP使用流程

**Comment by fazhen** [comment]
申请开发 deadline：2018-09-10 size：0.4 @fushang318

**Comment by fazhen** [comment]
首次培训（20180903）部分视频：https://shimo.im/docs/JFH3pPSW5Og7od1e

再次培训（20180905）部分视频：

**Comment by fazhen** [comment]
经两次培训，南希已经了解icp工作流程，基本掌握issue创建流程，ICP认证通过 @fushang318

**Comment by fushang318** [comment]
1
