### ISSUE TITLE
BMI各年龄段肥胖取值范围

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#22]
背景：https://github.com/sibbay-ai/public/issues/266#issuecomment-379617792
目的：根据需求查询整理各年龄段BMI范围
Deadline:2018-04-10 @ax003d

**Comment by fazhen** [comment]
已根据需求完成BMI取值范围，详见附件，如有疑问随时联系。
[BMI范围.docx](https://github.com/sibbay-ai/medical/files/1893669/BMI.docx)
@ax003d

**Comment by ax003d** [comment]
@fazhen 按照 ICP 规定，deadline 需要单独写一个 comment

**Comment by fazhen** [comment]
好的，我还没看新的流程，我看一下，马上修改，关于BMI如果有疑问可以随时和我联系 @ax003d

**Comment by ax003d** [comment]
@fushang318 @fazhen 这个由谁录入数据库？

**Comment by fazhen** [comment]
这个我不是太清楚 @ax003d @fushang318

**Comment by fazhen** [comment]
申请size:0.3 @ax003d

**Comment by fushang318** [comment]
@fazhen @ax003d 
后台管理有一个录入医学指标数据的功能

@ax003d 你说的这个BMI是否是一个单独的医学指标记录？
如果是的话，这个操作就是需要  @fazhen 录入一个新的医学指标

**Comment by fazhen** [comment]
deadline:2018-04-15

**Comment by fazhen** [comment]
这个需要我再协助什么吗 @ax003d

**Comment by ax003d** [comment]
@fazhen 按照 @fushang318 的说法，应该是由你来录入新的医学指标

**Comment by ax003d** [comment]
目前我在代码中 hard code
```
        # http://bmi.name/cn/
        medindex_infos['BMI'] = MedindexInfo(
            range=MedindexRange(
            low=[0, 18.4],
            normal=[18.5, 24.9],
            slight=[25, 29.9],
            moderate=[30, 39.9],
            severe=[40, 100]
        ))
```

**Comment by fazhen** [comment]
好的，我先看一下后台系统 @ax003d
