### ISSUE TITLE
关于小白社区增加“健康之树及健康果园”游戏功能的初步设想

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#220]
主要工作内容：针对刘总提出的“小白社区开发类似蚂蚁森林游戏功能”的相关事宜，就小白社区增加“健康之树”，延伸开发“健康果园”相关事宜形成初步想法，为后期工作提供思路参考。@georgeliuyu@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-09-15 size：0.6 @fazhen

**Comment by kimgrace6** [comment]
工作成果详见：https://shimo.im/docs/deb48689e0ab4751/ 点击链接查看「关于小白社区增加」，或复制链接用石墨文档 App 打开@georgeliuyu@fazhen

**Comment by fazhen** [comment]
刘总，这个issue是否可以关闭，你是否已经验收？ @georgeliuyu

**Comment by fazhen** [comment]
请 @fushang318 修改标签，并合并 @fushang318

**Comment by georgeliuyu** [comment]
@kimgrace6 @fazhen 这个游戏有意思，可以考虑细化
