### ISSUE TITLE
小白奖励模型脚本

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#221]
主要工作内容：将略显复杂的小白四级奖励模型转化为生动形象、言简意赅的卡通宣传片对于小白的上线推广至关重要，该脚本即为卡通宣传片的文字脚本。@georgeliuyu@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-09-15 size：1 @georgeliuyu @fazhen

**Comment by fazhen** [comment]
刘总，该issue是否可以关闭 @georgeliuyu

**Comment by fazhen** [comment]
李飞，金老师这里修改分支名称后，创建了两个pr，这个是否影响icp统计？ @fushang318

**Comment by fazhen** [comment]
请修改标签，合并分支 @fushang318

**Comment by fushang318** [comment]
不会 @fazhen
