### ISSUE TITLE
小白奖励模型脚本2

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#223]
将略显复杂的小白四级奖励模型转化为生动形象、言简意赅的卡通宣传片对于小白的上线推广至关重要，该脚本即为卡通宣传片的文字脚本2，该脚本更接近刘总的奖励模型原型，供大家对比脚本1进行讨论。@georgeliuyu@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-09-15 size：1 @georgeliuyu @fazhen

**Comment by kimgrace6** [comment]
相关工作成果详见：https://shimo.im/docs/b404720f314142b9/ 点击链接查看「小白奖励模型脚本２」，或复制链接用石墨文档 App 打开@georgeliuyu@fazhen

**Comment by fazhen** [comment]
刘总，这个issue是否可以关闭 @georgeliuyu

**Comment by fazhen** [comment]
请修改标签，合并分支 @fushang318

**Comment by fushang318** [comment]
@fazhen 好了

**Comment by georgeliuyu** [comment]
@kimgrace6 
关于场景要理顺的一些关系：
1、记录能产生价值；
2、医生的留言能给用户产生价值，医生能得到收获；
3、记录的隔天收取的场景；
4、获得下级的记录价值的场景；（多级）
5、收藏的场景（不提出来，这样产生的数量会更多）
