### ISSUE TITLE
症状问询规则沟通及后续工作规划

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#230]
主要工作：沟通症状问询工作，规划后续症状问询推进工作。

**Comment by fazhen** [comment]
会议沟通详情：https://shimo.im/docs/Rd9DbyE8UVI7C305
后续工作规划：
1.统计系统中现有症状，合并或删减现有系统症状中晦涩、重复、症状特征性描述等术语；
2.根据整理后症状，重现按照解剖部位进行症状分类；
3.根据新版MRI互动规则，撰写一份症状样例实际运行后形成固定规则；
4.安排兼职人员根据新版症状问询规则，撰写症状问询脚本
@fushang318

**Comment by kimgrace6** [comment]
好的
