### ISSUE TITLE
现有系统症状整理

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#237]
主要工作：
现有系统症状整理：
1. 保留临床常见，有进一步追问意义的症状；
2. 排除“哈欠、打嗝、色斑”等无进一步追问价值的症状
3.  合并表意重复的症状
4.  排除疾病、临床专业词汇
      @fushang318

**Comment by fazhen** [comment]
申请开发 deadline：2018-09-30 size：1.2 @fushang318

**Comment by fazhen** [comment]
成果：
原640个症状，经初步筛选后建议保留约150个，详见：https://shimo.im/sheet/JriZAsGFMss4rPCv/Qqt7x/ 

原数据均未修改，请筛选查看
 
0：保留
1：删除
2：合并
3：修改措辞
@ben7th @fushang318 @georgeliuyu

**Comment by fushang318** [comment]
@fazhen 好，我先合并
后续推进，需要分批进行
1. 你标记为删除的数据，我通过脚本批量对这些数据进行隐藏操作，隐藏后的数据，用户不能通过增加入口找到，但是已经有的用户数据不受影响
2. 你标记为修改措辞的数据，我通过脚本批量处理，没有问题
3. 你标记为合并的数据，这个目前没有机制可以处理，我想到的合并方式如下


既然是合并就是 N 条数据合并成一条，其中肯定是隐藏了 N-1 条，留下了一条，所以需要知道 N-1 分别是谁，1 是谁
然后系统开发一个映射表，把映射关系记录下来，记录的内容是
N-1 是谁，映射的目标 1 是谁

这个映射关系目前不会对用户在小程序中的体验造成影响，也就是用户通过小程序看自己的历史数据 被合并的数据和被隐藏的数据一样，还是照常显示，只是不能在通过增加入口找到

但是这个映射关系可能后续会用在数据统计上

**Comment by fushang318** [comment]
@fazhen 这批数据中并没有合并吧

**Comment by fushang318** [comment]
后台管理可以开发一个合并功能，实现我刚才说的逻辑

**Comment by fushang318** [comment]
嗯，第一步是需要这么处理的
但是后续数据统计，是需要考虑多条映射成一条的逻辑的，当然这个功能不紧急，但是比较重要吧？

**Comment by fazhen** [comment]
是的 @fushang318

**Comment by fazhen** [comment]
https://github.com/sibbay-ai/medical/issues/237

**Comment by fushang318** [comment]
贾老师，你整理的症状数据，我已经全部重新导入到生产环境了

**Comment by fazhen** [comment]
收到
