### ISSUE TITLE
小白游戏及奖励模型脚本细化

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#243]
结合前期设计的小白“健康之树及健康果园”设想、奖励模型脚本，本着提升游戏趣味性及参与度、将奖励模型现实镜像化的原则，将游戏中的每个环节落实到奖励模型的框架之下，在本周会上分享给大家，供平台参考。@georgeliuyu@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-09-30 size：1.6 @georgeliuyu @fazhen

**Comment by fazhen** [comment]
本issue中涉及的工作内容，如果size评估有误，可申请变更，不必另外创建新的issue  @kimgrace6

**Comment by georgeliuyu** [comment]
@kimgrace6 暂不建议细化

**Comment by kimgrace6** [comment]
好的 @georgeliuyu @fazhen

**Comment by kimgrace6** [comment]
已申请变更size@fazhen

**Comment by fazhen** [comment]
请修改标签 @fushang318
