### ISSUE TITLE
ICP培训视频录制

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#244]
主要工作：录制并icp培训视频 @fushang318

**Comment by fazhen** [comment]
详见：
https://shimo.im/docs/XkzpY1TYHOMris8a/ 《ICP培训视频》
https://shimo.im/docs/8k7S0Sds8ZQssEUi/ 《ICP培训视频使用说明》

请审核，特别是“8.审核issue创建”和“9.deadline变更”这两项内容，如无修改意见，我将提交给新同事培训使用
@fushang318

**Comment by fazhen** [comment]
已经按照意见完成修改
1.https://shimo.im/docs/MABHD971H48soi8R/ 《ICP培训视频使用说明V2》
2.https://shimo.im/docs/GJLIpJYHlAUr37Jf/ 《ICP培训视频V2》

视频“6.创建PR”和“9.deadline和size变更”为修改后视频 @fushang318

**Comment by fazhen** [comment]
申请增加size：0.1 @fushang318 ，修改视频 @fushang318

**Comment by fushang318** [comment]
@fazhen 好了
