### ISSUE TITLE
临床常见症状添加人员调整

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#26]
上月症状添加人员返修率高、效率低，已经淘汰一人，为配合2018-05-01上线工作，计划重新招募4-5人，补充临床症状。
**主要工作内容**：招募兼职，讲解症状提交规则以及snomed编码查询方法

故申请5个小白后台管理系统**症状添加人员**账号，账户名分别为：Rose 、begonia、chrysanthemum、Lilac、Carnation

开放功能权限，请参考现有兼职

@fushang318

**Comment by fazhen** [comment]
deadline:2018-04-15 size:0.2 @fushang318

**Comment by fushang318** [comment]
密码不要透露，编辑掉吧

**Comment by fushang318** [comment]
已经微信给你了

**Comment by fushang318** [comment]
你的这个ISSUE的工作内容我没有看明白，你调整一下吧，不然不利于后续EI的投票，
因为如果大家看不懂就不会对你的工作进行客观的评价
