### ISSUE TITLE
症状问询第三次复核

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#269]
主要工作：复核特症状中有无重复，并进行修改；小白系统后台修改隐藏症状，统一症状名称；检查、症状、特征问询系统中不存在的整理，查询概述等

**Comment by fazhen** [comment]
申请开发 deadline：2018-11-01 size：1.5 @fushang318

**Comment by fazhen** [comment]
说明：
1.再次复核后发现，有统一症状对应不同编码的情况，故部分症状有修改，详见文件夹《修改》；
2.检查、主症状、特征问询等系统中不存在的词条整理完毕，请统一导入后台；
详见
https://shimo.im/folder/3fKChYPpq7Q14XLb @fushang318

**Comment by fushang318** [comment]
1. 三个文件批量导入数据库，主症状，检查，特征症状

**Comment by fushang318** [comment]
我导入数据后，重新生成了对比表 https://shimo.im/folder/X7J0rCiM9wIf1xp9

其中有十几个 特征症状还是不存在，你看看原因

比如皮疹
你整理的导入表中
sctid-271807003 皮疹 

但是 对比表中的皮疹是


sctid-162415008 | 皮疹

**Comment by fazhen** [comment]
收到

**Comment by fazhen** [comment]
不存在症状已经做了修改和调整，请讲文件夹“修改”中症状重新导入https://shimo.im/folder/BzMrUSplfbsbjc9i @fushang318

**Comment by fushang318** [comment]
导入修改后，导出了对比表，还是有问题
https://shimo.im/folder/oD1uOqok9gEvAzu3

我肉眼过了一遍，有问题的已经标记为红色，你也肉眼过一遍吧
其中  
特征症状有三处错误，需要改  
检查有两处错误，需要改
主症状有几处名字不对应的错误，可改可不改，因为这个名字不影响用户使用，只影响我们自己看

你看一下，看看是改数据库还是问询文件，如果改问询文件把增量修改的给我

**Comment by fushang318** [comment]
@fazhen

**Comment by fazhen** [comment]
申请增加size：0.5，申请理由：在V3版本的基础上又进行两次审核，并针对性的完成修改 @fushang318

**Comment by fushang318** [comment]
变更 deadline: 2018-11-15
