### ISSUE TITLE
小白健康广告词征集文稿撰写

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#273]
工作内容：撰写小白健康广告词征集文稿，兼顾小白推广及受众特殊性的双重需求，达到广告词征集的目的。@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-11-13 size：1.2 @fazhen

**Comment by kimgrace6** [comment]
相关工作成果详见：https://shimo.im/docs/1f35b40a79a04074/ 点击链接查看「广告征集」，或复制链接用石墨文档 App 打开@fazhen

**Comment by kimgrace6** [comment]
根据刘总今日最新指示，本项工作成果作为“软文广告”本身，而非当初的“广告征集”，特此说明。@fazhen

**Comment by fazhen** [comment]
经金老师与刘总沟通，本issue提交物调整为小白宣传文案，请修改标签 @fushang318
