### ISSUE TITLE
review大白的关系建立文字确认

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#274]
主要内容：针对大白的关系建立，对文字部分进行review，详见：https://github.com/sibbay-ai/feedback/issues/60@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-11-14 size：0.2 @fazhen

**Comment by kimgrace6** [comment]
相关工作成果，详见：https://github.com/sibbay-ai/feedback/issues/60 @fazhen

**Comment by fazhen** [comment]
请修改标签 @fushang318

**Comment by fazhen** [comment]
已经审核并合并，如果无其他疑问，请关闭该issue @kimgrace6

**Comment by fushang318** [comment]
1
