### ISSUE TITLE
丁香园等专业医学网站广告位沟通

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#281]

**Comment by fazhen** [comment]
主要工作：联系丁香园等专业网站，对比价格、点击率等情况，为小白推广做准备。 @fushang318

**Comment by fazhen** [comment]
申请开发 deadline：2018-11-15 size：1.0 @fushang318

**Comment by fazhen** [comment]
经过与丁香园、医脉通销售以及其他医疗圈内朋友沟通，基于小白正式发布前预热的目的，建议以软文和硬广结合的方式进行，且均放在移动端。

     丁香园：APP-丁香智汇-最新资讯头条图片1天、微博-丁香园官方微博1条、微信-丁香园官方微信-1级菜单7天
     医脉通：首页-轮播焦点图、首页-资讯信息流广告、多平台发布

两个平台推广费用均在两万元左右，具体价格及形式见附件标红内容；

我推荐使用丁香园：1.医生间话题讨论热度而言，丁香园更具有优势；2.医生的数量级有优势；3.
宣传渠道更多：微信、微博、APP，且微博可@医疗圈大V，易于信息扩散。

 刘总，明天与您再次电话沟通 @georgeliuyu 

 其余同事请知悉 @ben7th @fushang318 @aixinhuang @kimgrace6 @akakenle 

[医脉通推广报价.xlsx](https://github.com/sibbay-ai/medical/files/2576560/default.xlsx)
[尘微丁香园-活动报价.xlsx](https://github.com/sibbay-ai/medical/files/2576561/-.xlsx)

**Comment by georgeliuyu** [comment]
@fazhen 好
