### ISSUE TITLE
SHT首发有感文稿

### ISSUE THREAD

**Issue by kimgrace6** [sibbay-ai/medical#283]
工作内容：针对SHT首发，撰写文稿，记录一个见证者的感受。@fazhen

**Comment by kimgrace6** [comment]
申请开发 deadline：2018-11-30 size：0.7 @fazhen

**Comment by kimgrace6** [comment]
相关工作成果详见：https://shimo.im/docs/9f87999eb9e34073/ 《行善的锦鲤》，可复制链接后用石墨文档 App 打开@fazhen

**Comment by fazhen** [comment]
交付物已经提交宋亮 @ben7th 

请修改标签 @fushang318
