### ISSUE TITLE
OMAHA年会参展

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#289]
OMAHA联盟即将于2019年1月11日至12日举行年会，小白健康作为该联盟的机构会员，有五张参会门票和免费参展权益。为配合参展海报的制作，有以下工作内容，需要配合完成

1.企业介绍（350字以内）、企业logo、二维码，为保证打印效果，请尽量提供矢量图，请 @ben7th 配合提供

 2.根据模板，设计海报，请 @fangrongxaing 配合完成，相关模板及样例见https://shimo.im/docs/yripMDSnFrgyY04k/ 《海报模板及样例》

**Comment by fazhen** [comment]
OMAHA年会参会剩余4个名额，如有ICPER或其他贡献者有意思参加，请在12月10号之前告知我，以便提前报名。

会议简介：
2019年1月11-12日，由浙江数字医疗卫生技术研究院OMAHA主办的“开放医疗与健康联盟第四届年会暨浙江数字医疗卫生技术研究院成立十周年高峰论坛——数智未来，赋能新医疗”将在杭州举办。
　　本届年会规模将达800人，大会邀请全国最权威的医疗机构、信息技术企业、专家学者等代表带来精彩的主题演讲，分享最前沿的技术应用，探讨医疗信息技术产业的机遇以及最新动向，为行业提供最有价值的信息分享和前瞻性预测。

[2019年OMAHA年会会员单位参展邀请函.pdf](https://github.com/sibbay-ai/medical/files/2648823/2019.OMAHA.pdf)

@ben7th

**Comment by fazhen** [comment]
申请开发 deadline：2018-12-12 size：0.3 @fushang318

**Comment by fushang318** [comment]
1

**Comment by fazhen** [comment]
申请增加size：0.3，理由：公司简介多次变更，共反复修改至少五个版本，以及沟通协调工作等。公司简介版本，详见https://shimo.im/docs/iXg2O4eh9X0v8nrE
@fushang318

**Comment by fushang318** [comment]
变更 deadline: 2019-01-15 size: 0.6
