### ISSUE TITLE
量表调研报告（思维导图）

### ISSUE THREAD

**Issue by Yijia-Zhou** [sibbay-ai/medical#306]
[医学量表相关 | ProcessOn免费在线作图,在线流程图,在线思维导图](https://www.processon.com/view/link/5dd3bbede4b048f2dc9668b2)

**Comment by Yijia-Zhou** [comment]
申请开发 deadline: 2019-12-17 @bqx619

**Comment by Yijia-Zhou** [comment]
size:2.5

**Comment by bqx619** [comment]
因为格式, 作废
