### ISSUE TITLE
血压、血糖、心率指标

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#31]
背景：https://github.com/sibbay-ai/cooperation-issues/issues/563
主要工作，查询整理血压、血糖、心率指标，供设计参考

**Comment by fazhen** [comment]
申请开发 deadline:2018-04-26 size:0.1 @fushang318

**Comment by fazhen** [comment]
已经完成，请参考https://shimo.im/docs/l5c7nxiaH6Men16t @fushang318

**Comment by fushang318** [comment]
我突然想到，用户在新用户引导中，不见得会输入血压，血糖这些信息，所以内容反馈其实可以是，血压和血糖的一些基本常识，而不是一个输入值的反馈，更合适

**Comment by fushang318** [comment]
@fazhen
