### ISSUE TITLE
组织并参与“健康记录专家”会议

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#33]
背景：https://github.com/sibbay-ai/cooperation-issues/issues/577
主要工作：制定邀请函及ZOOM会议使用流程，邀请医学兼职参会，并总结会议内容。

**Comment by fazhen** [comment]
申请开发 deadline:2018-04-27 size:0.3 @shero3

**Comment by fazhen** [comment]
请 @shero3 审核邀请函https://shimo.im/docs/1ziGDuuiNcMIID2A
 请刘总知悉
@georgeliuyu

**Comment by georgeliuyu** [comment]
@fazhen 要有明确的提交物

**Comment by fazhen** [comment]
会议总结：
1. 以高血压和糖尿病为例，探索引导用户坚持记录的方法；2.主要记录症状、用药、监测指标变化、检查单据、影响其诊疗行为的事件；3. 阶段性总结用户记录情况，给予关怀；4. 高血压及糖尿病监督中应对话术、健康数据对用户本身的重要性论述，需要有专人负责，我会单独安排；5. 小白现有功能介绍，我整理后发给各位医学兼职；

会议邀请函、会议系统使用流程附件、会议总结，这些算吗 @georgeliuyu

**Comment by fazhen** [comment]
如果这些不算， @shero3 就不要打标签了，我会把这个ISSUE关闭

**Comment by georgeliuyu** [comment]
@fazhen 我的建议是：  
小白的社区是尊重和信任，是否是提交物应该由你来确定。
