### ISSUE TITLE
心脑血管疾病风险评估 计算方案设计

### ISSUE THREAD

**Issue by Yijia-Zhou** [sibbay-ai/medical#330]
https://shimo.im/sheets/xqGrRyccDQ9x3XRw/MODOC/
![心脑血管疾病风险评估 计算方案设计](https://user-images.githubusercontent.com/22675861/76682520-b12d6c80-6637-11ea-8fb6-597fcb6ea682.png)

**Comment by Yijia-Zhou** [comment]
#327

**Comment by Yijia-Zhou** [comment]
申请开发 deadline: 2020-03-20 size:1 @bqx619

**Comment by bqx619** [comment]
1
