### ISSUE TITLE
每天更新疫情互动中的疫情状况统计信息

### ISSUE THREAD

**Issue by Yijia-Zhou** [sibbay-ai/medical#334]
从1月20日到3月5日，共40余天，早期为手动进行统计，后改为直接复制/截图央视新闻客户端统计信息

**Comment by Yijia-Zhou** [comment]
![批注 2020-03-15 101128](https://user-images.githubusercontent.com/22675861/76693875-fb9a0200-66a6-11ea-8824-19357b7c009b.png)

**Comment by Yijia-Zhou** [comment]
申请开发 deadline: 2020-03-20 size:1.8 @bqx619

**Comment by bqx619** [comment]
1
