### ISSUE TITLE
饮食 tips 添加、重构

### ISSUE THREAD

**Issue by Yijia-Zhou** [sibbay-ai/medical#348]
新写、重写了部分 tips, 并重新调整了 tips 间的关系，使整体更清晰、能更好地配合饮食优化微行动

**Comment by Yijia-Zhou** [comment]
[饮食tips（模板化）](https://www.processon.com/view/link/5f002ce3e401fd3908b09598)

**Comment by Yijia-Zhou** [comment]
申请开发 deadline: 2020-07-20 size:0.6 @bqx619

**Comment by bqx619** [comment]
1

**Comment by bqx619** [comment]
1
