### ISSUE TITLE
健康数据监测

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#35]
背景：https://github.com/sibbay-ai/cooperation-issues/issues/585
主要工作，查询健康数据相关资料，撰写健康数据监测重要性的文章。

**Comment by fazhen** [comment]
申请开发 deadline:2018-05-07 size:0.4 @alisahuxu

**Comment by fazhen** [comment]
相关文章已经撰写完成，详见https://shimo.im/docs/ANRHWQHpr6kQTI1E @alisahuxu @georgeliuyu

**Comment by fazhen** [comment]
刘总，这个issue你帮我打上标签吧 @georgeliuyu

**Comment by georgeliuyu** [comment]
变更 deadline:2018-05-16
