### ISSUE TITLE
认知行为疗法及Woebot调研

### ISSUE THREAD

**Issue by Yijia-Zhou** [sibbay-ai/medical#350]
#### 依据

- 书籍[《认知行为疗法入门》](<https://weread.qq.com/web/reader/c4c32ff071d3be56c4c5e23>)
- 知乎live [“认知行为疗法CBT核心技能及实操”](<https://www.zhihu.com/lives/1173284081881559040>)
- [Woebot app](<https://play.google.com/store/apps/details?id=com.woebot>)

#### 结果

于 2020.08.11 进行报告，主要收获点为通过启发和引导用户/寻求咨询者思考进行心理疏导的方式（自行分析对错、利害，制定方案）

https://www.processon.com/view/link/5f3792477d9c0806d418b6ce

**Comment by Yijia-Zhou** [comment]
申请开发 deadline: 2020-08-20 size:2.5 @bqx619

**Comment by bqx619** [comment]
1

**Comment by bqx619** [comment]
1
