### ISSUE TITLE
TIA血压监测

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#40]
介绍小白健康在监测短暂性脑缺血发作（TIA）患者血压中的优势；
主要工作：查询TIA相关资料以及小白健康白皮书，梳理出文档文档大纲，并最终以PPT的格式进行描述。

**Comment by fazhen** [comment]
申请开发 deadline 2018-05-15  size:1.2 
@georgeliuyu

**Comment by fazhen** [comment]
TIA血压监测PPT文档撰写完成，请查收https://pan.baidu.com/s/1oAoSN-5RcdVD8vwO-J4c-w
@georgeliuyu

**Comment by fushang318** [comment]
变更 deadline:2018-05-15 编写格式不对
