### ISSUE TITLE
设计互动内容-review

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#46]
背景https://github.com/sibbay-ai/cooperation-issues/issues/679
设计内容审核

**Comment by fazhen** [comment]
1.关于“AD：您记得最近一次例假是什么时候吗？”个人感觉应该添加“不记得”选项，与后续问题的关系请斟酌；
2.余医学相关审核已经完成，详见https://shimo.im/docs/QiGDWm64rLcZI6dF

@fushang318 @skytian1 @bqx619

**Comment by skytian1** [comment]
@fazhen 贾老师，您发的那个石墨文档，我没有权限，查看不了。可否帮忙添加下权限，谢谢

**Comment by skytian1** [comment]
@fazhen 贾老师，已经按照您review的内容，进行更改，请查看，谢谢https://shimo.im/docs/0qZtp2DbPwkWXUz9

**Comment by skytian1** [comment]
https://shimo.im/docs/qaAjeEmHRyYheoVA 还有这个是非经期/孕期/哺乳期的文案，是否OK @fazhen

**Comment by skytian1** [comment]
已经review完成，请帮忙merge，谢谢 @fushang318
