### ISSUE TITLE
健康记录专家培训相关资料撰写

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#48]
为推动健康健康专家留言，组织培训；
主要工作：撰写培训相关资料及组织培训

**Comment by fazhen** [comment]
申请开发 deadline：2018-05-30 size：0.4  @georgeliuyu

**Comment by fazhen** [comment]
相关培训资料，详见
https://shimo.im/docs/fXFrtzCq8fc53paP

https://shimo.im/docs/NgAZCOrsYBcDN1P0

https://shimo.im/sheet/WrqrS3uZvuUAw3KB/cHjeA

@georgeliuyu

**Comment by fazhen** [comment]
刘总，麻烦帮我打上标签 @georgeliuyu

**Comment by georgeliuyu** [comment]
@fazhen 图表没有权限

**Comment by fazhen** [comment]
变更 deadline：2018-06-15 @georgeliuyu 表格权限已经添加

**Comment by fazhen** [comment]
变更 deadline：2018-06-15 @georgeliuyu 表格权限已经添加

**Comment by fazhen** [comment]
变更 deadline：2018-06-15

**Comment by fushang318** [comment]
变更 deadline：2018-06-15
