### ISSUE TITLE
第三批新人培训

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#66]
主要工作：培训新的健康记录专家并整理备案信息

**Comment by fazhen** [comment]
申请开发：deadline：2018-06-05 size：0.2 @georgeliuyu

**Comment by fazhen** [comment]
培训视频：https://shimo.im/docs/2DZnn16EThs1UDjG
备案信息：https://shimo.im/sheet/n1e6ae6UzRYtqUMd/8pp8G @georgeliuyu

**Comment by fushang318** [comment]
变更 deadline: 2018-06-05
