### ISSUE TITLE
小白“记录”功能子菜单分类

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#84]
背景：在“记录”中的列表分类混乱（如报告单、生活点滴、成长点滴等），可能会影响用户记录，建议重新分类；
主要工作：在小白健康后台管理系统，医学检验分类管理中重新添加分类

**Comment by fazhen** [comment]
申请开发：deadline：2018-07-15 size：0.1 @fushang318

**Comment by fazhen** [comment]
申请开发 deadline：2018-07-15 size：0.1 @fushang318

**Comment by fazhen** [comment]
已添加完成 @fushang318

**Comment by fushang318** [comment]
额，工作内容没看懂，你还是写清楚一些，不然影响投票时的判断，你会吃亏哦

**Comment by fazhen** [comment]
已经重新描述工作内容 @fushang318

**Comment by fushang318** [comment]
1
