### ISSUE TITLE
新症状添加的规则制定

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#9]
背景：小白健康现有症状不足以满足用户需求，尚需补充；
目的：制定症状添加规则。
@shero3 申请开发size:0.5 Deadline:2018-02-28

**Comment by fazhen** [comment]
规则见https://shimo.im/docs/wb7qqjwOUKIhIzvs

**Comment by fazhen** [comment]
李飞，申请2个可以添加新症状的账号（仅有添加新症状权限而无审核权限）和1个审核账号（仅有审核权限而无添加新症状权限）；目前仅尝试新症状添加，只开通“症状和分类管理”功能即可。
@fushang318

**Comment by fushang318** [comment]
@fazhen 把习惯的账号名告诉我吧

**Comment by fazhen** [comment]
Shero，麻烦帮我打一下size标签吧 @shero3
