### ISSUE TITLE
“唯凯健康管理医生工作室”--小白功能介绍文档尝试

### ISSUE THREAD

**Issue by fazhen** [sibbay-ai/medical#98]
主要工作：录制“血压”、“症状添加”两个视频，联系设计同事转化为动态图，制作文档介绍样例，尝试与专家沟通可行的功能介绍文档

**Comment by fazhen** [comment]
申请开发 deadline：2018-07-15 size：0.1 @georgeliuyu

**Comment by fazhen** [comment]
成果：
1.在录制“血压”视频过程中，发现同一时间点无法重复保存血压的情况，并已向技术反馈；
2.制作样例介绍文档https://shimo.im/docs/rUiw0sfLH8guXhae/

**Comment by georgeliuyu** [comment]
@fazhen 你的icp先由 @fushang318 管理。
